#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use MaviDurakIO\Advertisement\Commands\Instagram;

$application = new Application();
$application->add(new Instagram());
$application->run();